import type { DocumentStatus } from './api';

export const documentStatus = (status: DocumentStatus): string => ({
  queued: '等待處理中',
  processing: '處理中...',
  ready: '已就緒',
  error: '處理失敗',
}[status]);

export const documentTypeLabel = (type: 'pdf' | 'url' | 'youtube' | 'text'): string => ({
  pdf: 'PDF',
  url: 'URL',
  youtube: 'YouTube',
  text: '文字',
}[type]);

export const uiCopy = {
  actions: {
    add: '新增',
    cancel: '取消',
    close: '關閉',
    create: '建立',
    delete: '刪除',
    download: '下載',
    edit: '編輯',
    export: '匯出',
    preview: '預覽',
    save: '儲存',
  },
  sourcesPanel: {
    title: '資料來源',
    selectProject: '選擇專案',
    newProject: '新增專案',
    addSource: '新增來源',
    addSources: '新增來源',
    search: '搜尋資料來源',
    selectProjectToStart: '選擇或建立專案以開始使用',
    empty: '尚無資料來源',
    noResults: '找不到資料來源',
    uploadHint: '點選「新增來源」以上傳 PDF、URL 或 YouTube 影片',
    projectNamePrompt: '輸入專案名稱：',
    selectProjectFirst: '請先選擇或建立專案',
    deleteDocumentConfirmation: '確定要刪除此文件嗎？',
    createProjectFailed: '建立專案失敗',
    deleteDocumentFailed: '刪除文件失敗',
  },
  chat: {
    askAnything: '針對資料來源提出任何問題...',
    addSourcesToStart: '新增資料來源後即可開始對話',
    newConversation: '新增對話',
    newChat: '新增對話',
    sourcesReady: '個資料來源已就緒',
  },
  projectDialog: {
    title: '建立新專案',
    name: '專案名稱',
    nameRequired: '請輸入專案名稱',
    namePlaceholder: '例如：研究論文、會議紀錄',
    description: '說明',
    descriptionPlaceholder: '選填：說明此專案的內容',
    help: '專案可協助你整理文件與對話。',
    sourceHelp: '你可以將 PDF、URL、YouTube 影片等內容加入專案。',
    creating: '建立中...',
    created: '已建立！',
    success: '專案已建立！',
    createFailed: '建立專案失敗',
    create: '建立專案',
  },
  upload: {
    file: '檔案',
    add: '新增',
    dragAndDrop: '將檔案拖曳到這裡，或',
    browse: '選取檔案',
    maxFileSize: '檔案大小上限：',
    youtubeUrlPlaceholder: '輸入 YouTube URL...',
    urlPlaceholder: '輸入網站 URL...',
    selectedFiles: '已選擇的檔案：',
    uploading: '上傳中...',
    upload: '上傳',
    validUrl: '請輸入有效的 URL',
    uploadFailed: '上傳失敗，請再試一次。',
    uploadUrlFailed: '上傳失敗，請檢查 URL 後再試一次。',
    selectFilesOrUrl: '請選擇檔案或輸入 URL',
  },
  conversation: {
    title: '對話',
    noConversations: '尚無對話',
    startNewChat: '建立新對話以開始使用',
    selectProjectFirst: '請先選擇專案',
    deleteConfirmation: '確定要刪除此對話嗎？',
    today: '今天',
    yesterday: '昨天',
    thisWeek: '本週',
    thisMonth: '本月',
    older: '更早',
  },
  settings: {
    title: '設定',
    general: '一般',
    apiKeys: 'API 金鑰',
    dataStorage: '資料與儲存空間',
    notifications: '通知',
    security: '安全性',
    about: '關於',
  },
  documentPreview: {
    pdfUnavailable: '無法預覽 PDF',
    extractedText: '擷取的文字：',
    transcript: '逐字稿：',
    contentUnavailable: '無法預覽內容',
    copyContent: '複製內容',
    openInNewTab: '在新分頁開啟',
    fullscreen: '全螢幕',
    exitFullscreen: '離開全螢幕',
    processingNotice: '此文件仍在處理中，部分功能可能尚無法使用。',
  },
  exportDialog: {
    conversation: '對話',
    project: '專案',
    description: '以偏好的格式匯出「{name}」',
    chooseFormat: '選擇匯出格式：',
    exported: '已匯出！',
    exporting: '匯出中...',
    exportFailed: '匯出失敗，請再試一次。',
  },
  documentStatus,
  documentTypeLabel,
};
